blog/urls.py
from django.urls import path
from .views import (
    SearchView,
    IndexView,
    PostListView,
    PostDetailView,
    PostCreateView,
    PostUpdateView,
    PostDeleteView
)

app_name = "blog"

urlpatterns = [
    path('', IndexView.as_view(), name='home'),
    path('blog/', PostListView.as_view(), name='post-list'),
    path('search/', SearchView.as_view(), name='search'),
    path('create/', PostCreateView.as_view(), name='post-create'),
    path('post/<pk>/', PostDetailView.as_view(), name='post-detail'),
    path('post/<pk>/update/', PostUpdateView.as_view(), name='post-update'),
    path('post/<pk>/delete/', PostDeleteView.as_view(), name='post-delete'),
]

core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('', include('marketing.urls')),

    path('tinymce/', include('tinymce.urls')),
    path('accounts/', include('allauth.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

marketing/urls.py
from django.urls import path
from .views import email_list_signup

app_name = "marketing"

urlpatterns = [
    path('email-signup/', email_list_signup, name='email-list-signup'),
]

blog/models.py
from tinymce import HTMLField
from django.db import models
from django.contrib.auth import get_user_model
from django.urls import reverse

User = get_user_model()


class PostView(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey('Post', on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username


class Author(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    profile_picture = models.ImageField()

    def __str__(self):
        return self.user.username


class Category(models.Model):
    title = models.CharField(max_length=20)

    def __str__(self):
        return self.title


class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    timestamp = models.DateTimeField(auto_now_add=True)
    content = models.TextField()
    post = models.ForeignKey(
        'Post', related_name='comments', on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username


class Post(models.Model):
    title = models.CharField(max_length=100)
    overview = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)
    content = HTMLField()
    # comment_count = models.IntegerField(default = 0)
    # view_count = models.IntegerField(default = 0)
    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    thumbnail = models.ImageField()
    categories = models.ManyToManyField(Category)
    featured = models.BooleanField()
    previous_post = models.ForeignKey(
        'self', related_name='previous', on_delete=models.SET_NULL, blank=True, null=True)
    next_post = models.ForeignKey(
        'self', related_name='next', on_delete=models.SET_NULL, blank=True, null=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:post-detail', kwargs={
            'pk': self.pk
        })

    def get_update_url(self):
        return reverse('blog:post-update', kwargs={
            'pk': self.pk
        })

    def get_delete_url(self):
        return reverse('blog:post-delete', kwargs={
            'pk': self.pk
        })

    @property
    def get_comments(self):
        return self.comments.all().order_by('-timestamp')

    @property
    def comment_count(self):
        return Comment.objects.filter(post=self).count()

    @property
    def view_count(self):
        return PostView.objects.filter(post=self).count()

blog/forms.py
from django import forms
from tinymce import TinyMCE
from .models import Post, Comment


class TinyMCEWidget(TinyMCE):
    def use_required_attribute(self, *args):
        return False


class PostForm(forms.ModelForm):
    content = forms.CharField(
        widget=TinyMCEWidget(
            attrs={'required': False, 'cols': 30, 'rows': 10}
        )
    )

    class Meta:
        model = Post
        fields = ('title', 'overview', 'content', 'thumbnail',
                  'categories', 'featured', 'previous_post', 'next_post')


class CommentForm(forms.ModelForm):
    content = forms.CharField(label='', widget=forms.Textarea(attrs={
        'class': 'form-control',
        'placeholder': 'Type your comment',
        'id': 'usercomment',
        'rows': '4'
    }))

    class Meta:
        model = Comment
        fields = ('content',)
        label = ''

blog/views.py
from django.db.models import Count, Q
from django.contrib import messages
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.shortcuts import render, get_object_or_404, redirect, reverse
from django.views.generic import View, ListView, DetailView, CreateView, UpdateView, DeleteView

from .forms import CommentForm, PostForm
from .models import Post, Author, PostView
from marketing.forms import EmailSignupForm
from marketing.models import Signup

form = EmailSignupForm()


def get_author(user):
    qs = Author.objects.filter(user=user)
    if qs.exists():
        return qs[0]
    return None


def get_category_count():
    queryset = Post \
        .objects \
        .values('categories__title') \
        .annotate(Count('categories__title'))
    return queryset


class SearchView(View):
    def get(self, request, *args, **kwargs):
        queryset = Post.objects.all()
        query = request.GET.get('q')
        if query:
            queryset = queryset.filter(
                Q(title__icontains=query) |
                Q(overview__icontains=query)
            ).distinct()
        context = {
            'queryset': queryset
        }
        return render(request, 'search_results.html', context)


class IndexView(View):
    form = EmailSignupForm()

    def get(self, request, *args, **kwargs):
        featured = Post.objects.filter(featured=True)
        latest = Post.objects.order_by('-timestamp')[0:3]
        context = {
            'object_list': featured,
            'latest': latest,
            'form': self.form
        }
        return render(request, 'index.html', context)

    def post(self, request, *args, **kwargs):
        email = request.POST.get("email")
        new_signup = Signup()
        new_signup.email = email
        new_signup.save()
        messages.info(request, "Successfully subscribed")
        return redirect("blog:home")


class PostListView(ListView):
    form = EmailSignupForm()
    model = Post
    template_name = 'blog.html'
    context_object_name = 'queryset'
    paginate_by = 5

    def get_context_data(self, **kwargs):
        category_count = get_category_count()
        most_recent = Post.objects.order_by('-timestamp')[:3]
        context = super().get_context_data(**kwargs)
        context['most_recent'] = most_recent
        context['page_request_var'] = "page"
        context['category_count'] = category_count
        context['form'] = self.form
        return context


class PostDetailView(DetailView):
    model = Post
    template_name = 'post.html'
    context_object_name = 'post'
    form = CommentForm()

    def get_object(self):
        obj = super().get_object()
        if self.request.user.is_authenticated:
            PostView.objects.get_or_create(
                user=self.request.user,
                post=obj
            )
        return obj

    def get_context_data(self, **kwargs):
        category_count = get_category_count()
        most_recent = Post.objects.order_by('-timestamp')[:3]
        context = super().get_context_data(**kwargs)
        context['most_recent'] = most_recent
        context['page_request_var'] = "page"
        context['category_count'] = category_count
        context['form'] = self.form
        return context

    def post(self, request, *args, **kwargs):
        form = CommentForm(request.POST)
        if form.is_valid():
            post = self.get_object()
            form.instance.user = request.user
            form.instance.post = post
            form.save()
            return redirect(reverse("blog:post-detail", kwargs={
                'pk': post.pk
            }))


class PostCreateView(CreateView):
    model = Post
    template_name = 'post_create.html'
    form_class = PostForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Create'
        return context

    def form_valid(self, form):
        form.instance.author = get_author(self.request.user)
        form.save()
        return redirect(reverse("blog:post-detail", kwargs={
            'pk': form.instance.pk
        }))


class PostUpdateView(UpdateView):
    model = Post
    template_name = 'post_create.html'
    form_class = PostForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Update'
        return context

    def form_valid(self, form):
        form.instance.author = get_author(self.request.user)
        form.save()
        return redirect(reverse("blog:post-detail", kwargs={
            'pk': form.instance.pk
        }))


class PostDeleteView(DeleteView):
    model = Post
    success_url = '/blog'
    template_name = 'post_confirm_delete.html'

templates/admin_bar.html
{% block admincss %}
    <style>
        .sidebar {
            height: 100%;
            width: 0;
            position: fixed;
            top: 0;
            left: 0;
            background-color: #022F40;
            overflow-x: hidden;
            transition: 0.5s;
            padding-top: 60px;
            opacity: .99;
            z-index: 999;
        }

        .sidebar a {
            padding: 8px 8px 8px 32px;
            text-decoration: none;
            font-size: 25px;
            color: #818181;
            display: block;
            transition: 0.3s;
        }

        .sidebar a:hover {
            color: #f1f1f1;
        }

        #main {
            transition: margin-left .5s;
            padding: 16px;
        }

        #adminSidebar a:first-child {
            position: relative;
            top: -70px;
        }

        .newPost input {
            color: #fffafa;
            border: none;
            background: rgba(0, 216, 255, .3);
            padding: 15px 15px;
            height: 60px;
            -webkit-border-radius: 3px 30px 3px 30px;
            -moz-border-radius: 3px 30px 3px 30px;
            border-radius: 3px 30px 3px 30px;
        }

        .newPost textarea {
            color: #fffafa;
            border: none;
            background: rgba(0, 216, 255, .3);
            padding: 15px 15px;
            -webkit-border-radius: 3px 50px 3px 50px;
            -moz-border-radius: 3px 50px 3px 50px;
            border-radius: 3px 50px 3px 50px;
        }

        .newPost select {
            color: #fffafa;
            border: none;
            background: rgba(0, 216, 255, .3);
            padding: 15px 15px;
            min-height: 60px;
            -webkit-border-radius: 3px 30px 3px 30px;
            -moz-border-radius: 3px 30px 3px 30px;
            border-radius: 3px 30px 3px 30px;
        }

        .newPost {
            padding: 50px 0;
            background: #022f40;
            background: -webkit-linear-gradient(315deg, #1B4353 0%, #022f40 100%);
            background: -o-linear-gradient(315deg, #1B4353 0%, #022f40 100%);
            background: linear-gradient(315deg, #1B4353 0%, #022f40 100%);
            filter: progid:DXImageTransform.Microsoft.gradient(startColorstr='#1B4353', endColorstr='#022f40', GradientType=1);
        }

        /* On smaller screens, where height is less than 450px, change the style of the sidenav (less padding and a smaller font size) */
        @media screen and (max-height: 450px) {
            .sidebar {
                padding-top: 15px;
            }

            .sidebar a {
                font-size: 18px;
            }
        }
    </style>
{% endblock %}

<div id="adminSidebar" class="sidebar">
    <a href="javascript:void(0)" class="noBtm closeBtn text-right w-100" onclick="closeNav()"><i
            class="fal fa-times"></i></a>
    <a href="{% url 'blog:post-create' %}">New Post</a>
</div>

{% block adminjs %}
    <script>
        function openNav() {
            document.getElementById("adminSidebar").style.width = "250px";
            document.getElementById("main").style.marginLeft = "250px";
        }

        function closeNav() {
            document.getElementById("adminSidebar").style.width = "0";
            document.getElementById("main").style.marginLeft = "0";
        }
    </script>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html>

{% include "head.html" %}

<body>

    {% include 'header.html' %}

    {% if messages %}
        <ul class="messages">
            {% for message in messages %}
                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}

    {% block content %}
    {% endblock content %}

    {% include 'newsletter.html' %}
    {% include 'footer.html' %}
    {% if user.is_superuser %}
        {% include 'admin_bar.html' %}
    {% endif %}
    {% include 'scripts.html' %}

</body>

</html>

templates/blog.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <section class="page-top-section" style="background: url({% static 'img/page-header.jpg' %});">
        <div class="page-info">
            <h2>Blog</h2>
            <div class="breadcrumb">
                <a href="">Home</a> /
                <span>Blog</span>
            </div>
        </div>
    </section>
    <section class="blog-page">
        <div class="container">
            <div class="row">
                <div class="col-xl-9 col-lg-8 col-md-7">
                    <ul class="blogFilter">
                        <li><a class="jl-btn" href="#">React</a></li>
                        <li><a class="jl-btn" href="#">Django</a></li>
                        <li><a class="jl-btn" href="#">Bootstrap</a></li>
                        <li><a class="jl-btn" href="#">Python</a></li>
                    </ul>
                    {% for post in queryset %}
                        <div class="blogItem">
                            <img src="{{ post.thumbnail.url }}" alt="#" class="itemThumb blogThumb"/>
                            <div class="itemContent textBox whiteText">
                                <div class="postDetails">
                                    <div class="row">
                                        <div class="col-12">
                                            <span>
                                                <i class="fal fa-calendar"></i> {{ post.timestamp|timesince }} ago
                                            </span>
                                            <span>
                                                <i class="fal fa-archive"></i>
                                                {% for cat in post.categories.all %}
                                                    <a href="#">{{ cat }}</a>{% if not forloop.last %}, {% endif %}
                                                {% endfor %}
                                            </span>
                                            <span>
                                                <i class="fal fa-user"></i> {{ post.author }}
                                            </span>
                                            <span>
                                                <i class="fal fa-edit"></i> {{ post.comment_count }}
                                            </span>
                                            <span>
                                                <i class="fal fa-eye"></i> {{ post.view_count }}
                                            </span>
                                            <h3>{{ post.title }}</h3>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="col-md-8">
                                            <p>{{ post.overview|truncatechars:290 }}</p>
                                        </div>
                                        <div class="col-md-4">
                                            <a href="{{ post.get_absolute_url }}" class="viewArticle">
                                                View Article <i class="fal fa-arrow-right"></i>
                                            </a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>
                <div class="col-xl-3 col-lg-4 col-md-5 rightSidebar game-page-sideber">
                    <div id="stickySidebar">
                        <div class="widget-item">
                            {% include 'sidebar.html' with most_recent=most_recent category_count=category_count %}
                        </div>
                    </div>
                </div>

                {% if is_paginated %}

                    <nav aria-label="Page navigation example">
                        <ul class="pagination pagination-template d-flex justify-content-center">
                            {% if page_obj.has_previous %}
                                <li class="page-item"><a
                                        href="?{{ page_request_var }}={{ page_obj.previous_page_number }}"
                                        class="page-link"> <i class="fa fa-angle-left"></i></a></li>
                            {% endif %}
                            <li class="page-item">
                                <a href="?{{ page_request_var }}={{ page_obj.number }}"
                                   class="page-link active">{{ page_obj.number }}</a>
                            </li>
                            {% if page_obj.has_next %}
                                <li class="page-item"><a
                                        href="?{{ page_request_var }}={{ page_obj.next_page_number }}"
                                        class="page-link"> <i class="fa fa-angle-right"></i></a></li>
                            {% endif %}
                        </ul>
                    </nav>

                {% endif %}
            </div>
        </div>
    </section>

{% endblock content %}

templates/footer.html
{% load static %}
<footer class="footer text-center">
    <div class="container">
        <div class="d-block">
            <p class="mwlf">
                Made with <span style="color: #d6204e;">&#10084;</span> for
            </p>
        </div>
        <div class="footer-right-pic">
            <a class="noBtm" href="https://www.djangoproject.com/" target="_blank">
                <img src="{% static 'img/django-logo.png' %}" class="ml-6" width="50" alt="">
            </a>
        </div>
        <div class="footer-right-pic">
            <a class="noBtm" href="https://reactjs.org/">
                <img src="{% static 'img/react-js-logo.png' %}" class="mr-6" width="50" alt="">
            </a>
        </div>
        <p class="float-left copyright">
            <small>&copy; Copyright 2018, Jannick.La</small>
        </p>
    </div>
</footer>

templates/head.html
{% load static %}
  <!DOCTYPE html>
<html lang="en">
<head>

	<meta charset="UTF-8">
	<meta name="description" content="Jannick La -  A React and Django blog">
	<meta name="keywords" content="react, django, webdevelopment, coders blog">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">

	<title>{{ Jannick.la }}</title>

	<link href="{% static 'img/favicon.ico' %}" rel="shortcut icon" />
	<link href="https://fonts.googleapis.com/css?family=Raleway:400,400i,500,500i,700,700i,900,900i" rel="stylesheet">
	<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}"/>
	<link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}"/>
	<link rel="stylesheet" href="{% static 'fonts/fontawesome-pro-5.13.0-web/css/light.min.css' %}"/>
	<link rel="stylesheet" href="{% static 'css/slicknav.min.css' %}"/>
	<link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}"/>
	<link rel="stylesheet" href="{% static 'css/animate.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/prismjs.css' %}"/>
	<link rel="stylesheet" href="{% static 'css/style.css' %}"/>
    {% block admincss %}{% endblock %}

	<!--[if lt IE 9]>
		<script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
	    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
	<![endif]-->

</head>

templates/header.html
<header class="headerSection">
    <div class="header">
        <div class="headerBar d-flex">
            <a href="{% url 'blog:home' %}" class="noBtm siteLogo logoFont">
                jannick.la
            </a>
            <nav class="top-nav-area w-100">
                <div class="user-panel">
                    <a href="">Login</a> / <a href="">Register</a>
                </div>
                <ul class="main-menu primary-menu">
                    <li><a href="{% url 'blog:post-list' %}" class="noBtm">Blog</a>
                        <ul class="sub-menu">
                            <li><a href="game-single.html" class="noBtm">Django</a></li>
                            <li><a href="game-single.html" class="noBtm">React</a></li>
                            <li><a href="game-single.html" class="noBtm">Frontend</a></li>
                            <li><a href="game-single.html" class="noBtm">Backend</a></li>
                        </ul>
                    </li>
                    <li><a href="contact.html" class="noBtm">Contact</a></li>
                    {% if user.is_superuser %}
                    <li><a href="#" onclick="openNav()" class="openbtn noBtm">Admin</a></li>
                    {% endif %}
                </ul>
            </nav>
        </div>
    </div>
</header>

templates/newsletter.html
<section class="newsletter-section">
    <div class="container">
        <h2>Get my E-Book for <strong>free</strong></h2>
        <form class="newsletter-form" action="{% url 'marketing:email-list-signup' %}" method="POST">
            <input type="text" placeholder="myawesome@email.com">
            <button class="jl-btn">Get it</button>
        </form>
        <span class="whiteText">
            <small>By getting the free e-book you'll subscripe to our newsletter</small>
        </span>
    </div>
</section>

templates/post.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <section class="page-top-section set-bg" style="background: url({% static 'img/page-header.jpg' %});">
        <div class="page-info">
            <h2>Games</h2>
            <div class="breadcrumb">
                <a href="{% url 'blog:home' %}">Home</a> /
                <span>Games</span>
            </div>
        </div>
    </section>
    <section class="games-single-page">
        <div class="container">
            <div class="game-single-preview">
                <img src="{{ post.thumbnail.url }}" alt="" />
            </div>
            <div class="row">
                <div class="col-xl-9 col-lg-8 col-md-7 game-single-content">
                    <div class="postDetails">
                        <span><i class="fal fa-calendar"></i> {{ post.timestamp|timesince }} ago</span>
                        <span><i class="fal fa-archive"></i>
                            {% for cat in post.categories.all %}
                                <a href="#">{{ cat }}</a>{% if not forloop.last %},{% endif %}
                            {% endfor %}
                                    </span>
                        <span><i class="fal fa-user"></i> {{ post.author }}</span>
                        <span><i class="fal fa-edit"></i> {{ post.comment_count }}</span>
                        <span><i class="fal fa-eye"></i> {{ post.view_count }}</span>
                    </div>
                    <h2 class="gs-title">{{ post.title }}</h2>
                    <div class="blogContentTxt">
                        {{ post.content | safe }}
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            {% if post.previous_post %}
                                <div class="prevNextBtn">
                                    <a href="{{ post.previous_post.get_absolute_url }}"><i class="fal fa-arrow-left"></i> PREVIOUS</a>
                                    <h6 class="text-center">{{ post.previous_post.title }}</h6>
                                </div>
                            {% endif %}
                        </div>
                        <div class="col-md-6">
                            {% if post.next_post %}
                                <div class="prevNextBtn text-right">
                                    <a href="{{ post.next_post.get_absolute_url }}">Next <i class="fal fa-arrow-right"></i></a>
                                    <h6 class="text-center">{{ post.next_post.title }}</h6>
                                </div>
                            {% endif %}
                        </div>
                    </div>
                    <div class="postComments">
                        <header>
                            <h6>
                                Post Comments
                                <span class="no-of-comments">({{ post.comments.count }})</span>
                            </h6>
                        </header>
                        {% for comment in post.get_comments %}
                            <div class="comment">
                                <div class="comment-header d-flex justify-content-between">
                                    <div class="user d-flex align-items-center">
                                        <div class="image">
                                            {% if comment.user.author %}
                                                <img src="{{ comment.user.author.profile_picture.url }}"
                                                     alt="..." class="img-fluid rounded-circle">
                                            {% else %}
                                                <img src="{% static 'img/user.svg' %}" alt="..."
                                                     class="img-fluid rounded-circle">
                                            {% endif %}
                                        </div>
                                        <div class="title"><strong>{{ comment.user.username }}</strong><span
                                                class="date ml-3">{{ comment.timestamp|timesince }} ago</span></div>
                                    </div>
                                </div>
                                <div class="comment-body">
                                    <p>{{ comment.content }}</p>
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                    {% if request.user.is_authenticated %}
                        <div class="addComment">
                            <header>
                                <h3 class="h6 logoFont">Leave a reply</h3>
                            </header>
                            <form method="POST" action="." class="commentingForm">
                                {% csrf_token %}
                                <div class="row">
                                    <div class="form-group col-md-12">
                                        {{ form }}
                                    </div>
                                    <div class="form-group col-md-12">
                                        <button class="jl-btn">Add Comment</button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    {% else %}
                        <a href="{% url 'blog:account_login' %}" class="btn btn-primary">Login to comment</a>
                    {% endif %}
                </div>
                <div class="col-xl-3 col-lg-4 col-md-5 rightSidebar game-page-sideber">
                    <div id="stickySidebar">
                        <div class="widget-item">
                            {% include 'sidebar.html' with most_recent=most_recent category_count=category_count %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock content %}

templates/scripts.html
{% load static %}
<script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
<script src="{% static 'js/prismjs.js' %}"></script>
<script src="{% static 'js/main.js' %}"></script>
{% block adminjs %}{% endblock %}

templates/sidebar.html
<aside id="sticky">
    <!-- Widget [Search Bar Widget]-->
    <div class="widget search">
        <header>
            <h3 class="h6">Search the blog</h3>
        </header>
        <form action="{% url 'blog:search' %}" class="searchForm">
            <div class="input-group mb-3">
                <input type="text" name="q" class="form-control" placeholder="search..."/>
                <div class="input-group-append">
                    <button class="btn btn-outline-secondary" type="submit">
                        <i class="fal fa-search"></i>
                    </button>
                </div>
            </div>
        </form>
    </div>
    <!-- Widget [Latest Posts Widget]        -->
    <div class="widget latest-posts">
        <header>
            <h3 class="h6">Latest Posts</h3>
        </header>
        <div class="blogPosts">
            {% for post in most_recent %}
                <a href="{{ post.get_absolute_url }}" class="noBtm">
                    <div class="item d-flex align-items-center">
                        <div class="image"><img src="{{ post.thumbnail.url }}" alt="..." class="img-fluid"></div>
                        <div class="title"><strong>{{ post.title }}</strong>
                            <div class="d-flex align-items-center">
                                <div class="views mr-3"><i class="fal fa-eye"></i> {{ post.view_count }}</div>
                                <div class="comments"><i class="fal fa-edit"></i> {{ post.comment_count }}</div>
                            </div>
                        </div>
                    </div>
                </a>
            {% endfor %}
        </div>
        <!-- Widget [Categories Widget]-->
        <div class="widget categories">
            <header>
                <h3 class="h6">Categories</h3>
            </header>
            {% for cat in category_count %}
                <div class="item d-flex justify-content-between">
                    <a href="#">{{ cat.categories__title }}</a><span>{{ cat.categories__title__count }}</span>
                </div>
            {% endfor %}
        </div>
</aside>